import 'package:minamitra_pembudidaya_mobile/feature/products/repositories/products_response.dart';

final List<ProductsResponseData> dummyDiscountProduct = [
  ProductsResponseData(
    id: '1',
    code: '123',
    name: 'Ikan Lele',
    categoryId: '1',
    itemCategoryParId: '1',
    categoryName: 'Ikan',
    unitId: '1',
    unitName: 'Kg',
    sellPrice: '20000',
    buyPrice: '15000',
    stock: '100',
    supplierId: '1',
    supplierName: 'Joko',
    proteinPercent: '20',
    lemakPercent: '10',
    seratKasarPercent: '5',
    kadarAbuPercent: '3',
    kadarAirPercent: '10',
    note:
        'Pakan Haida HDMA1 merupakan pakan ikan bibit terapung memiliki kandungan protein 35%. Diformulasikan dengan nutrisi yang lengkap, pakan berkualitas ini dapat membantu mengoptimalkan pertumbuhan ikan mas/patin Anda. Pakan ini cocok digunakan untuk fase starter. Kemasan : 1 sak 20 Kg.',
    imageUrl: 'https://cdn.mitra3m.id/2024/10/image/HAIDA+HDMA1-1730185448.jpg',
    activeBool: true,
  ),
  ProductsResponseData(
    id: '1',
    code: '123',
    name: 'Ikan Lele',
    categoryId: '1',
    itemCategoryParId: '1',
    categoryName: 'Ikan',
    unitId: '1',
    unitName: 'Kg',
    sellPrice: '20000',
    buyPrice: '15000',
    stock: '100',
    supplierId: '1',
    supplierName: 'Joko',
    proteinPercent: '20',
    lemakPercent: '10',
    seratKasarPercent: '5',
    kadarAbuPercent: '3',
    kadarAirPercent: '10',
    note:
        'Pakan Haida HDMA1 merupakan pakan ikan bibit terapung memiliki kandungan protein 35%. Diformulasikan dengan nutrisi yang lengkap, pakan berkualitas ini dapat membantu mengoptimalkan pertumbuhan ikan mas/patin Anda. Pakan ini cocok digunakan untuk fase starter. Kemasan : 1 sak 20 Kg.',
    imageUrl: 'https://cdn.mitra3m.id/2024/10/image/HAIDA+HDMA1-1730185448.jpg',
    activeBool: true,
  ),
  ProductsResponseData(
    id: '1',
    code: '123',
    name: 'Ikan Lele',
    categoryId: '1',
    itemCategoryParId: '1',
    categoryName: 'Ikan',
    unitId: '1',
    unitName: 'Kg',
    sellPrice: '20000',
    buyPrice: '15000',
    stock: '100',
    supplierId: '1',
    supplierName: 'Joko',
    proteinPercent: '20',
    lemakPercent: '10',
    seratKasarPercent: '5',
    kadarAbuPercent: '3',
    kadarAirPercent: '10',
    note:
        'Pakan Haida HDMA1 merupakan pakan ikan bibit terapung memiliki kandungan protein 35%. Diformulasikan dengan nutrisi yang lengkap, pakan berkualitas ini dapat membantu mengoptimalkan pertumbuhan ikan mas/patin Anda. Pakan ini cocok digunakan untuk fase starter. Kemasan : 1 sak 20 Kg.',
    imageUrl: 'https://cdn.mitra3m.id/2024/10/image/HAIDA+HDMA1-1730185448.jpg',
    activeBool: true,
  ),
  ProductsResponseData(
    id: '1',
    code: '123',
    name: 'Ikan Lele',
    categoryId: '1',
    itemCategoryParId: '1',
    categoryName: 'Ikan',
    unitId: '1',
    unitName: 'Kg',
    sellPrice: '20000',
    buyPrice: '15000',
    stock: '100',
    supplierId: '1',
    supplierName: 'Joko',
    proteinPercent: '20',
    lemakPercent: '10',
    seratKasarPercent: '5',
    kadarAbuPercent: '3',
    kadarAirPercent: '10',
    note:
        'Pakan Haida HDMA1 merupakan pakan ikan bibit terapung memiliki kandungan protein 35%. Diformulasikan dengan nutrisi yang lengkap, pakan berkualitas ini dapat membantu mengoptimalkan pertumbuhan ikan mas/patin Anda. Pakan ini cocok digunakan untuk fase starter. Kemasan : 1 sak 20 Kg.',
    imageUrl: 'https://cdn.mitra3m.id/2024/10/image/HAIDA+HDMA1-1730185448.jpg',
    activeBool: true,
  ),
];
