// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBxS0RqF0On_KpW8d3caIYxiLiCoxlLRk',
    appId: '1:204455506381:web:59b9b02b6389f1c4fd1484',
    messagingSenderId: '204455506381',
    projectId: 'mitra3m-ae108',
    authDomain: 'mitra3m-ae108.firebaseapp.com',
    storageBucket: 'mitra3m-ae108.appspot.com',
    measurementId: 'G-8PP2PM4VY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67QM9ohMXQVSXqpI0JvUyWlTSb_U7dq0',
    appId: '1:204455506381:android:663a1f04864b28a7fd1484',
    messagingSenderId: '204455506381',
    projectId: 'mitra3m-ae108',
    storageBucket: 'mitra3m-ae108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUdfyrbcQ2ZCbOfbcWLOGp52hXJSG4NQo',
    appId: '1:204455506381:ios:d60c837799e6afd5fd1484',
    messagingSenderId: '204455506381',
    projectId: 'mitra3m-ae108',
    storageBucket: 'mitra3m-ae108.appspot.com',
    iosBundleId: 'com.example.minamitraPembudidayaMobile',
  );
}
